version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64 #require for mac
    container_name: skillbridge-sql
    environment:
      SA_PASSWORD: "Dorje123@"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    restart: no
volumes:
  sql-data: